---
title: "Statistical Learning"
author: "Ruilian Zhang"
date: "12/2/2021"
output: github_document
---

```{r}
library(tidyverse)
library(glmnet)

set.seed(11)
```


## Lasso

Predicting bwt

```{r}
bwt_df = 
  read_csv("data/birthweight.csv") %>% 
  janitor::clean_names() %>%
  mutate(
    babysex = as.factor(babysex),
    babysex = fct_recode(babysex, "male" = "1", "female" = "2"),
    frace = as.factor(frace),
    frace = fct_recode(frace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4", "other" = "8"),
    malform = as.logical(malform),
    mrace = as.factor(mrace),
    mrace = fct_recode(mrace, "white" = "1", "black" = "2", "asian" = "3", 
                       "puerto rican" = "4")) %>% 
  sample_n(200)
```

```{r}
y = bwt_df %>% pull(bwt)
x = model.matrix(bwt ~ ., bwt_df)[, -1] # get rib of first column of intercept
```

```{r}
lambda_grid = 10 ^ seq(3, -2, by = -0.1) # pre-specify lambda

lasso_fit = glmnet(x, y, lambda = lambda_grid)

lasso_cv = cv.glmnet(x, y, lambda = lambda_grid)

lambda_opt = lasso_cv$lambda.min
```


```{r}
lasso_fit %>% 
  broom::tidy() %>% 
  complete(term, lambda, fill = list(estimate = 0)) %>% 
  filter(term != "(Intercept)") %>% 
  ggplot(aes(x = log(lambda), y = estimate, group = term, color = term)) +
  geom_path() +
  geom_vline(xintercept = log(lambda_opt))
```


## Cluster pokemons

```{r}
pokemon_df = 
  read_csv("data/pokemon.csv") %>% 
  janitor::clean_names() %>% 
  select(speed, hp)
```

```{r}
pokemon_df %>% 
  ggplot(aes(x = hp, y = speed)) +
  geom_point()
```

Use K-means to identify clusters

```{r}
kmeans_fit = 
  kmeans(x = pokemon_df, centers = 3)
```

```{r}
pokemon_df %>% 
  broom::augment(kmeans_fit, .) %>% # model first, df second
  ggplot(aes(x = hp, y = speed, color = .cluster)) +
  geom_point()
```

